name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "kok"
        tag: "release"
